"""
Utils moduli
"""

from database import get_db_session
from .text_utils import escape_markdown, format_user_info
from .admin_utils import check_is_superadmin
from .user_utils import (
    get_user_by_telegram_id,
    create_or_update_user,
    get_all_users,
    get_active_users,
    get_users_count,
    get_active_users_count,
    set_user_role,
    add_admin,
    remove_admin,
    get_admins,
    update_user_media_preference,
)
from .keyboard_utils import (
    get_inline_keyboard,
    get_admin_main_keyboard,
    get_admin_stats_keyboard,
    get_admin_broadcast_keyboard,
    get_admin_broadcast_waiting_keyboard,
    get_admin_broadcast_running_keyboard,
    get_user_main_keyboard,
    get_user_profile_keyboard,
    get_user_settings_keyboard,
    get_guest_main_keyboard,
    get_guest_register_keyboard,
    get_guest_info_keyboard,
    get_mandatory_channels_keyboard,
    get_mandatory_channels_list_keyboard,
    get_channel_manage_keyboard,
)
from .broadcast_manager import broadcast_manager
from .channel_utils import (
    add_mandatory_channel,
    remove_mandatory_channel,
    get_mandatory_channels,
    get_mandatory_channel,
    check_user_subscription,
    check_all_mandatory_subscriptions,
    toggle_channel_status,
    get_channel_invite_link,
    build_subscription_keyboard,
)

__all__ = [
    "get_db_session",
    "escape_markdown",
    "format_user_info",
    "check_is_superadmin",
    "get_user_by_telegram_id",
    "create_or_update_user",
    "get_all_users",
    "get_active_users",
    "get_users_count",
    "get_active_users_count",
    "set_user_role",
    "add_admin",
    "remove_admin",
    "get_admins",
    "update_user_media_preference",
    "get_inline_keyboard",
    "get_admin_main_keyboard",
    "get_admin_stats_keyboard",
    "get_admin_broadcast_keyboard",
    "get_admin_broadcast_waiting_keyboard",
    "get_admin_broadcast_running_keyboard",
    "get_user_main_keyboard",
    "get_user_profile_keyboard",
    "get_user_settings_keyboard",
    "get_guest_main_keyboard",
    "get_guest_register_keyboard",
    "get_guest_info_keyboard",
    "get_mandatory_channels_keyboard",
    "get_mandatory_channels_list_keyboard",
    "get_channel_manage_keyboard",
    "add_mandatory_channel",
    "remove_mandatory_channel",
    "get_mandatory_channels",
    "get_mandatory_channel",
    "check_user_subscription",
    "check_all_mandatory_subscriptions",
    "toggle_channel_status",
    "get_channel_invite_link",
    "build_subscription_keyboard",
    "broadcast_manager",
]
